# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0be124c2fe1bc2a0c529442d2ba4ab776f4bbe4fce796566878742a3981860f97b1b1319471b3a4f0f7cd078e288b1a42849af4904e865f050e165432e0ee110

test:
  secret_key_base: ee9bd506686e72ac43d9427f37a3f8a76a5e7b0d0551002eec6c176e2a646c326088ac3b871f5caa4bdbd7d33647dc304e7b8c18a6df410b98ec35708f4bd549

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
